# Generated by Django 5.1.1 on 2024-10-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0004_remove_feedback_faculty_alter_feedback_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
